insert into Soldier (Personnel_ID, Rank) values (260508,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (630197,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (671198,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (304786,'Seren');
insert into Soldier (Personnel_ID, Rank) values (856605,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (608350,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (789063,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (510656,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (262284,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (467330,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (519539,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (428072,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (989611,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (559540,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (326729,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (866366,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (543863,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (962270,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (893064,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (601075,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (359547,'Seren');
insert into Soldier (Personnel_ID, Rank) values (492206,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (765098,'Seren');
insert into Soldier (Personnel_ID, Rank) values (765720,'Seren');
insert into Soldier (Personnel_ID, Rank) values (750616,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (763128,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (144769,'Seren');
insert into Soldier (Personnel_ID, Rank) values (138518,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (877172,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (458332,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (176301,'Seren');
insert into Soldier (Personnel_ID, Rank) values (867058,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (765491,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (864679,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (234811,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (155844,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (357550,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (840801,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (405808,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (588568,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (391470,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (120445,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (973324,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (751498,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (257777,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (311999,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (272268,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (424534,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (611184,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (426299,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (781732,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (968352,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (435729,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (347760,'Seren');
insert into Soldier (Personnel_ID, Rank) values (257675,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (463950,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (519327,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (631232,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (642499,'Seren');
insert into Soldier (Personnel_ID, Rank) values (596917,'Seren');
insert into Soldier (Personnel_ID, Rank) values (478602,'Seren');
insert into Soldier (Personnel_ID, Rank) values (356285,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (767545,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (420151,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (629632,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (268170,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (124457,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (365313,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (457342,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (101292,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (425875,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (979491,'Seren');
insert into Soldier (Personnel_ID, Rank) values (238402,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (124979,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (946312,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (222043,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (303551,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (510878,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (267362,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (292696,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (355988,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (814257,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (402346,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (780957,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (590565,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (953363,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (148335,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (530505,'Seren');
insert into Soldier (Personnel_ID, Rank) values (226592,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (980472,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (244304,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (821518,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (250765,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (629620,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (991616,'Seren');
insert into Soldier (Personnel_ID, Rank) values (627814,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (993415,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (537865,'Seren');
insert into Soldier (Personnel_ID, Rank) values (611253,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (467962,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (315602,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (189726,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (630042,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (519351,'Seren');
insert into Soldier (Personnel_ID, Rank) values (268194,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (473492,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (681909,'Seren');
insert into Soldier (Personnel_ID, Rank) values (110224,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (940443,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (362255,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (544929,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (322747,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (639943,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (974417,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (530366,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (756585,'Seren');
insert into Soldier (Personnel_ID, Rank) values (147576,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (660471,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (308043,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (193287,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (292010,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (206790,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (785817,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (107685,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (732078,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (801928,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (503829,'Seren');
insert into Soldier (Personnel_ID, Rank) values (579434,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (243685,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (433673,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (102141,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (962929,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (277696,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (679606,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (725718,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (463794,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (843307,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (950855,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (961876,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (486836,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (142762,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (844189,'Seren');
insert into Soldier (Personnel_ID, Rank) values (412819,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (221891,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (740901,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (904581,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (565835,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (241744,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (486448,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (613842,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (326150,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (922960,'Seren');
insert into Soldier (Personnel_ID, Rank) values (416352,'Seren');
insert into Soldier (Personnel_ID, Rank) values (366187,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (845784,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (854588,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (277572,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (553865,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (107547,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (502009,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (969883,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (797525,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (911554,'Seren');
insert into Soldier (Personnel_ID, Rank) values (981355,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (649376,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (252768,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (649973,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (743470,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (457376,'Seren');
insert into Soldier (Personnel_ID, Rank) values (342205,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (383920,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (909560,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (754567,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (462453,'Seren');
insert into Soldier (Personnel_ID, Rank) values (759337,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (171887,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (279361,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (817881,'Seren');
insert into Soldier (Personnel_ID, Rank) values (867836,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (430794,'Seren');
insert into Soldier (Personnel_ID, Rank) values (839294,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (747474,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (638335,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (435935,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (917576,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (176689,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (162912,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (860323,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (322612,'Sgan Aluf Bakhir');
insert into Soldier (Personnel_ID, Rank) values (215445,'Seren');
insert into Soldier (Personnel_ID, Rank) values (437674,'Sgan Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (802378,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (818225,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (898695,'Aluf Mishne');
insert into Soldier (Personnel_ID, Rank) values (880926,'Tat Aluf');
insert into Soldier (Personnel_ID, Rank) values (541968,'Sgan Aluf');
insert into Soldier (Personnel_ID, Rank) values (107271,'Rav Seren');
insert into Soldier (Personnel_ID, Rank) values (378526,'Aluf');
insert into Soldier (Personnel_ID, Rank) values (400704,'Tzir Aluf');
insert into Soldier (Personnel_ID, Rank) values (135573,'Aluf Mishne');
